export const LOGIN = "/auth/login";
export const SIGNUP = "/auth/register";
export const GET_USER_PROFILE = "/auth/profile";
export const REFRESH_TOKEN = "/auth/refresh-token";
export const VALIDATE_TOKEN = "/auth/validate-token";
export const LOGOUT = "/auth/logout";
export const ADDPRODUCT = "/product/";
export const FETCH_ALL_REVIEW = '/review';
export const ADD_REVIEW = '/review/products/';
export const FETCH_ALL_WHISHLIST ='/whishlist';
export const TOGGLE_WHISHLIST = '/whishlist/toggle'
export const WHISHLIST_COUNT = '/whishlist/count'
export const WHISHLIST_CLEAR = '/whishlist/clear'
